micronaut:
  application:
    name: clienteService

#datasources:
#  default:
#    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: ""
#    driverClassName: org.h2.Driver

datasources:
  default:
    url: ${JDBC_CONNECTION_STRING}
    username: ${JDBC_USER}
    password: ${JDB_PASSWORD}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    dialect: MYSQL

jpa.default.properties.hibernate.hbm2ddl.auto: update